### ISSUE TITLE
Я так понимаю это просто заготовка для тестов?

### ISSUE THREAD

**Issue by free-archer** [grumagargler/CommonTests#3]
Я так понимаю это просто заготовка для тестов, самих "дымовых" тестов нет?

**Comment by grumagargler** [comment]
Дымовой тест находится здесь: CommonTests/Общее/ДымовойТест.1cm.bsl
Этот тест открывает один за другим объекты, доступные в меню пользователя, запущенного тестируемого приложения. Если вам не подходит такая логика, напишите, обсудим, или приходите в чат.

**Comment by free-archer** [comment]
Спасибо, попробовал. Классная штука даже ошибки нашлись в рабочей базе ))
